import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { initializeLanguage } from '@inlang/paraglide-next'

import Providers from '@/core/providers'
import { languageTag } from '@/libs/localization/paraglide/runtime'

const geistSans = localFont({
  src: '../fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: '../fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'allbc',
  description: 'Generated by create next app',
}

const RootLayout: ({ children }: { children: any }) => Promise<JSX.Element> = async ({
  children,
}) => {
  await initializeLanguage()
  const locale = languageTag()
  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}

export default RootLayout
