import type { Metadata } from 'next'
import localFont from 'next/font/local'

import { FC, ReactNode } from 'react'

import Providers from '@/core/providers'
import {languageTag} from "@/libs/localization/paraglide/runtime";

const geistSans = localFont({
  src: '../fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: '../fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'allbc',
  description: 'Generated by create next app',
}

interface IRootLayoutProps {
  children: ReactNode
}

const RootLayout: FC<IRootLayoutProps> = ({ children }) => {
  const locale = languageTag();
  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers locale={locale}>{children}</Providers>
      </body>
    </html>
  )
}

export default RootLayout
