import {
  AddOffice,
  ArrDown,
  ArticleFirst,
  ArticleSecond,
  ArticleThird,
  Banner,
  BgBanRight,
  BlockFifth,
  BlockFirst,
  BlockFourth,
  BlockSecond,
  BlockSixth,
  BlockThird,
  BrokerEighth,
  BrokerFifth,
  BrokerFirst,
  BrokerFourth,
  BrokerNinth,
  BrokerSecond,
  BrokerSeventh,
  BrokerSixth,
  BrokerTenth,
  BrokerThird,
  BuilderEighth,
  BuilderFifth,
  BuilderFirst,
  BuilderFourth,
  BuilderNinth,
  BuilderSecond,
  BuilderSeventh,
  BuilderSixth,
  BuilderTenth,
  BuilderThird,
  CartPhoto,
  Emblem,
  Facebook,
  iconSrc,
  ImageLogo,
  Instagram,
  ItemFifth,
  ItemFirst,
  ItemFourth,
  ItemSecond,
  ItemSeventh,
  ItemSixth,
  ItemThird,
  Like,
  Linkedin,
  Man,
  NewsBan,
  OwnerEighth,
  OwnerFifth,
  OwnerFirst,
  OwnerFourth,
  OwnerNinth,
  OwnerSecond,
  OwnerSeventh,
  OwnerSixth,
  OwnerTenth,
  OwnerThird,
  Push,
  Search,
  Twiter,
} from '@/app/shared/images'

export const imagesMap = {
  ImageLogo: ImageLogo,
  Facebook: Facebook,
  Twiter: Twiter,
  Linkedin: Linkedin,
  Instagram: Instagram,
  ArrDown: ArrDown,
  Like: Like,
  Push: Push,
  Search: Search,
  AddOffice: AddOffice,
  Emblem: Emblem,
  Banner: Banner,
  BlockFirst: BlockFirst,
  BlockSecond: BlockSecond,
  BlockThird: BlockThird,
  BlockFourth: BlockFourth,
  BlockFifth: BlockFifth,
  BlockSixth: BlockSixth,
  CartPhoto: CartPhoto,
  BgBanRight: BgBanRight,
  BrokerFirst: BrokerFirst,
  BrokerSecond: BrokerSecond,
  BrokerThird: BrokerThird,
  BrokerFourth: BrokerFourth,
  BrokerFifth: BrokerFifth,
  BrokerSixth: BrokerSixth,
  BrokerSeventh: BrokerSeventh,
  BrokerEighth: BrokerEighth,
  BrokerNinth: BrokerNinth,
  BrokerTenth: BrokerTenth,
  OwnerFirst: OwnerFirst,
  OwnerSecond: OwnerSecond,
  OwnerThird: OwnerThird,
  OwnerFourth: OwnerFourth,
  OwnerFifth: OwnerFifth,
  OwnerSixth: OwnerSixth,
  OwnerSeventh: OwnerSeventh,
  OwnerEighth: OwnerEighth,
  OwnerNinth: OwnerNinth,
  OwnerTenth: OwnerTenth,
  BuilderFirst: BuilderFirst,
  BuilderSecond: BuilderSecond,
  BuilderThird: BuilderThird,
  BuilderFourth: BuilderFourth,
  BuilderFifth: BuilderFifth,
  BuilderSixth: BuilderSixth,
  BuilderSeventh: BuilderSeventh,
  BuilderEighth: BuilderEighth,
  BuilderNinth: BuilderNinth,
  BuilderTenth: BuilderTenth,
  NewsBan: NewsBan,
  iconSrc: iconSrc,
  ItemFirst: ItemFirst,
  ItemSecond: ItemSecond,
  ItemThird: ItemThird,
  ItemFourth: ItemFourth,
  ItemFifth: ItemFifth,
  ItemSixth: ItemSixth,
  ItemSeventh: ItemSeventh,
  Man: Man,
  ArticleFirst: ArticleFirst,
  ArticleSecond: ArticleSecond,
  ArticleThird: ArticleThird,
}
