import {
    ImageLogo,
    Facebook,
    Twiter,
    Linkedin,
    Instagram,
    ArrDown,
    Like,
    Push,
    Search,
    AddOffice,
    Emblem,
    Banner,
    BlockFirst,
    BlockSecond,
    BlockThird,
    BlockFourth,
    BlockFifth,
    BlockSixth,
    CartPhoto,
    BgBanRight,
    BrokerFirst,
    BrokerSecond,
    BrokerThird,
    BrokerFourth,
    BrokerFifth,
    BrokerSixth,
    BrokerSeventh,
    BrokerEighth,
    BrokerNinth,
    BrokerTenth,
    OwnerFirst,
    OwnerSecond,
    OwnerThird,
    OwnerFourth,
    OwnerFifth,
    OwnerSixth,
    OwnerSeventh,
    OwnerEighth,
    OwnerNinth,
    OwnerTenth,
    BuilderFirst,
    BuilderSecond,
    BuilderThird,
    BuilderFourth,
    BuilderFifth,
    BuilderSixth,
    BuilderSeventh,
    BuilderEighth,
    BuilderNinth,
    BuilderTenth,
    NewsBan,
    iconSrc,
    ItemFirst,
    ItemSecond,
    ItemThird,
    ItemFourth,
    ItemFifth,
    ItemSixth,
    ItemSeventh,
    Man,
    ArticleFirst,
    ArticleSecond,
    ArticleThird,
} from "@/app/shared/images";

export const imagesMap = {
    ImageLogo: ImageLogo,
    Facebook: Facebook,
    Twiter: Twiter,
    Linkedin: Linkedin,
    Instagram: Instagram,
    ArrDown: ArrDown,
    Like: Like,
    Push: Push,
    Search: Search,
    AddOffice: AddOffice,
    Emblem: Emblem,
    Banner: Banner,
    BlockFirst: BlockFirst,
    BlockSecond: BlockSecond,
    BlockThird: BlockThird,
    BlockFourth: BlockFourth,
    BlockFifth: BlockFifth,
    BlockSixth: BlockSixth,
    CartPhoto: CartPhoto,
    BgBanRight: BgBanRight,
    BrokerFirst: BrokerFirst,
    BrokerSecond: BrokerSecond,
    BrokerThird: BrokerThird,
    BrokerFourth: BrokerFourth,
    BrokerFifth: BrokerFifth,
    BrokerSixth: BrokerSixth,
    BrokerSeventh: BrokerSeventh,
    BrokerEighth: BrokerEighth,
    BrokerNinth: BrokerNinth,
    BrokerTenth: BrokerTenth,
    OwnerFirst: OwnerFirst,
    OwnerSecond: OwnerSecond,
    OwnerThird: OwnerThird,
    OwnerFourth: OwnerFourth,
    OwnerFifth: OwnerFifth,
    OwnerSixth: OwnerSixth,
    OwnerSeventh: OwnerSeventh,
    OwnerEighth: OwnerEighth,
    OwnerNinth: OwnerNinth,
    OwnerTenth: OwnerTenth,
    BuilderFirst: BuilderFirst,
    BuilderSecond: BuilderSecond,
    BuilderThird: BuilderThird,
    BuilderFourth: BuilderFourth,
    BuilderFifth: BuilderFifth,
    BuilderSixth: BuilderSixth,
    BuilderSeventh: BuilderSeventh,
    BuilderEighth: BuilderEighth,
    BuilderNinth: BuilderNinth,
    BuilderTenth: BuilderTenth,
    NewsBan: NewsBan,
    iconSrc: iconSrc,
    ItemFirst: ItemFirst,
    ItemSecond: ItemSecond,
    ItemThird: ItemThird,
    ItemFourth: ItemFourth,
    ItemFifth: ItemFifth,
    ItemSixth: ItemSixth,
    ItemSeventh: ItemSeventh,
    Man: Man,
    ArticleFirst: ArticleFirst,
    ArticleSecond: ArticleSecond,
    ArticleThird: ArticleThird,
};
