export { default as AddOffice } from './add_office.svg'
export { default as ArrDown } from './arr-down.svg'
export { default as IconArrow } from './arrow.svg'
export { default as Like } from './like.svg'
export { default as Push } from './push.svg'
export { default as Search } from './search.svg'
export { default as LikeIcon } from './wishlist.svg'
