// file generated by the Paraglide-Next init command
import { Middleware, Navigation, PrefixStrategy } from '@inlang/paraglide-next'
import type { AvailableLanguageTag } from '@/libs/localization/paraglide/runtime'  // Додайте тип для мови

// Стратегію залишаємо як є, але використовуємо правильний тип
export const strategy = PrefixStrategy<AvailableLanguageTag>({
  prefixDefault: 'never', // або 'always', залежно від ваших потреб
})

export const middleware = Middleware({ strategy })

export const { Link, useRouter, usePathname, redirect, permanentRedirect } = Navigation({
  strategy,
})

